tasks:
  - init: npm ci && npm i -g firebase-tools
    command: npm run build

additionalRepositories:
  - url: https://github.com/For-0/vocabustudy-internals
    checkoutLocation: vocabustudy-internals