name: Build
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: "npm"
      - run: npm ci
      - run: npm run build
        env:
          CF_API_TOKEN: '${{ secrets.CF_API_TOKEN }}'
          CF_ZONE_ID: '${{ secrets.CF_ZONE_ID }}'