name: Build and Deploy
on:
  workflow_call:
    inputs:
      artifact-retention-days:
        description: 'Number of days to retain build artifacts'
        required: false
        default: 1
        type: number
      expires:
        required: false
        default: "7d"
        type: string
      channelId:
        required: false
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: Cache node modules
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-npm-cache-
      - run: npm ci
        name: Install dependencies
      - run: npm run build
        name: Build
        env:
          CF_API_TOKEN: '${{ secrets.CF_API_TOKEN }}'
          CF_ZONE_ID: '${{ secrets.CF_ZONE_ID }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOCAB_U_STUDY }}'
          projectId: vocab-u-study
          target: "vocabustudy"
          expires: ${{ inputs.expires }}
          channelId: ${{ inputs.channelId }}